import React, { useLayoutEffect, useRef, useState, useEffect } from "react";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import "./App.css";
import { Sun, Moon } from "lucide-react";

gsap.registerPlugin(ScrollTrigger);

function App() {
  const pageRef = useRef(null);
  const heroRef = useRef(null);
  const cardsRef = useRef([]);
  const statRef = useRef([]);
  const brandsRef = useRef([]);
  const [theme, setTheme] = useState(() =>
    typeof window !== 'undefined' ? localStorage.getItem('theme') || 'light' : 'light'
  );
  const [mobileOpen, setMobileOpen] = useState(false);

  useEffect(() => {
    const root = document.documentElement;
    if (theme === 'dark') {
      root.classList.add('dark');
    } else {
      root.classList.remove('dark');
    }
    try {
      localStorage.setItem('theme', theme);
    } catch (e) {
      // ignore
    }
  }, [theme]);

  useLayoutEffect(() => {
    const mm = gsap.matchMedia(pageRef);
    mm.add("(prefers-reduced-motion: no-preference)", () => {
      const heroItems = heroRef.current?.querySelectorAll(".animate-hero");
      if (heroItems?.length) {
        gsap.from(heroItems, {
          y: 48,
          autoAlpha: 0,
          duration: 0.8,
          stagger: 0.16,
          ease: "power3.out",
        });
      }

      cardsRef.current.forEach((card, index) => {
        if (!card) return;
        gsap.from(card, {
          y: 40,
          autoAlpha: 0,
          duration: 0.7,
          ease: "power2.out",
          delay: index * 0.04,
          scrollTrigger: {
            trigger: card,
            start: "top 88%",
          },
        });
      });

      statRef.current.forEach((item) => {
        if (!item) return;
        gsap.from(item, {
          scale: 0.82,
          autoAlpha: 0,
          duration: 0.62,
          ease: "back.out(1.5)",
          scrollTrigger: {
            trigger: item,
            start: "top 90%",
          },
        });
      });

      gsap.from(".cta-panel", {
        y: 54,
        autoAlpha: 0,
        duration: 0.8,
        ease: "power3.out",
        scrollTrigger: {
          trigger: ".cta-panel",
          start: "top 82%",
        },
      });


      brandsRef.current.forEach((card, index) => {
        if (!card) return;
        gsap.from(card, {
          y: 30,
          autoAlpha: 0,
          duration: 0.6,
          ease: "power2.out",
          delay: index * 0.1,
          scrollTrigger: {
            trigger: card,
            start: "top 85%",
          },
        });
      });
    });

    return () => {
      mm.revert();
    };
  }, []);

  const features = [
    {
      title: "Smart Roof Mapping",
      body: "AI-based sun path analysis picks the best panel layout for your specific roof geometry.",
      icon: "01",
    },
    {
      title: "Battery Backup",
      body: "Store daytime energy and keep essentials running through outages with silent backup power.",
      icon: "02",
    },
    {
      title: "Live Energy App",
      body: "Track production, savings, and carbon impact in real time from your phone or desktop.",
      icon: "03",
    },
  ];

  const steps = [
    "Book a home solar audit",
    "Get a custom savings projection",
    "Install in as little as 10 days",
    "Monitor usage and optimize monthly",
  ];

  const stats = [
    { value: "40%", label: "Average bill reduction" },
    { value: "25yr", label: "Panel performance warranty" },
    { value: "3.2M", label: "kWh generated by clients" },
  ];

  const brandCosts = [
    { name: "Tata Power Solar", cost: "₹65,000 - ₹75,000", desc: "India's most trusted brand with end-to-end EPC services." },
    { name: "Waaree Energies", cost: "₹60,000 - ₹70,000", desc: "India's largest solar panel manufacturer with vast local networks." },
    { name: "Adani Solar", cost: "₹62,000 - ₹72,000", desc: "High-efficiency panels backed by the Adani Group." },
    { name: "Vikram Solar", cost: "₹60,000 - ₹68,000", desc: "Tier 1 module manufacturer offering highly reliable systems." },
    { name: "Loom Solar", cost: "₹65,000 - ₹80,000", desc: "Premium bifacial panels and advanced battery specialists." },
  ];

  return (
    <main
      ref={pageRef}
      className="solar-page min-h-screen bg-white text-slate-900 dark:bg-black dark:text-white"
    >
      <header className="sticky top-0 z-30 bg-white/60 dark:bg-black/60 backdrop-blur-sm">
        <div className="flex items-center justify-between px-6 py-3 max-w-7xl mx-auto">
          <div className="flex items-center gap-4">
            <div className="logo animate-hero text-lg md:text-xl font-bold tracking-wide">SOLAR NEST</div>
            <nav className="header-links animate-hero hidden md:flex gap-6 text-sm">
              <a className="hover:underline" href="#features">Features</a>
              <a className="hover:underline" href="#process">Process</a>
              <a className="hover:underline" href="#contact">Contact</a>
            </nav>
          </div>

          <div className="flex items-center gap-3">
            <button
              type="button"
              onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}
              className="px-3 py-1 rounded-md border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 text-sm"
              aria-label="Toggle theme"
            >
              {theme === 'dark' ? <Sun /> : <Moon />}
            </button>

            {/* mobile menu button */}
            <button
              type="button"
              onClick={() => setMobileOpen((s) => !s)}
              className="md:hidden p-2 rounded-md border ml-1"
              aria-label="Open menu"
              aria-expanded={mobileOpen}
            >
              <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                <path strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" d="M4 6h16M4 12h16M4 18h16" />
              </svg>
            </button>
          </div>
        </div>

        {/* Mobile menu panel */}
        <div className={`md:hidden ${mobileOpen ? 'block' : 'hidden'} border-t border-gray-100 dark:border-gray-800 bg-white dark:bg-black/80`}>
          <div className="px-6 py-4 space-y-3">
            <a className="block text-sm" href="#features" onClick={() => setMobileOpen(false)}>Features</a>
            <a className="block text-sm" href="#process" onClick={() => setMobileOpen(false)}>Process</a>
            <a className="block text-sm" href="#contact" onClick={() => setMobileOpen(false)}>Contact</a>
          </div>
        </div>
      </header>

      <section
        ref={heroRef}
        className="max-w-7xl mx-auto px-6 py-12 grid grid-cols-1 md:grid-cols-2 gap-8 items-center text-center"
      >
        <div className="hero-copy animate-hero max-w-xl mx-auto">
          <p className="kicker text-sm uppercase text-indigo-600 font-semibold">Solar Home Project</p>
          <h1 className="animate-hero text-3xl md:text-5xl font-extrabold leading-tight mt-3">Power Your Home With Sunlight, Not Surprises.</h1>
          <p className="hero-text animate-hero mt-4 text-lg text-slate-700 dark:text-slate-300">
            Build an energy-independent home with clean solar production, smart storage, and transparent savings from day one.
          </p>
          <div className="hero-actions animate-hero mt-6 flex gap-3 justify-center">
            <button type="button" className="bg-indigo-600 text-white px-4 py-2 rounded-md shadow hover:bg-indigo-500">Get Free Estimate</button>
            <button type="button" className="border border-indigo-600 text-indigo-600 dark:text-indigo-300 px-4 py-2 rounded-md">Watch Demo</button>
          </div>
        </div>

        <aside className="hero-card animate-hero bg-gray-50 dark:bg-gray-900 p-6 rounded-lg shadow mx-auto">
          <p className="card-label text-sm text-slate-500 dark:text-slate-400">Projected Monthly Savings</p>
          <p className="card-amount text-3xl font-semibold mt-2">$186</p>
          <p className="card-subtext text-sm text-slate-500 dark:text-slate-400 mt-1">Based on 6.8kW rooftop setup and 8.5h avg sun/day.</p>
          <div className="sun-track mt-4" aria-hidden="true">
            <span className="block w-3 h-3 rounded-full bg-yellow-400" />
          </div>
        </aside>
      </section>

      <section id="features" className="max-w-7xl mx-auto px-6 py-12 text-center">
        <h2 className="text-2xl font-bold mb-6">Everything You Need For A Future-Ready Home</h2>
        <div className="feature-grid grid grid-cols-1 sm:grid-cols-3 gap-6 place-items-center">
          {features.map((feature, index) => (
            <article
              key={feature.title}
              ref={(el) => {
                cardsRef.current[index] = el;
              }}
              className="feature-card p-6 bg-white dark:bg-gray-900 rounded-lg shadow hover:translate-y-1 transition-transform text-center"
            >
              <p className="feature-id text-indigo-600 font-bold">{feature.icon}</p>
              <h3 className="mt-3 text-lg font-semibold">{feature.title}</h3>
              <p className="mt-2 text-slate-600 dark:text-slate-300">{feature.body}</p>
            </article>
          ))}
        </div>
      </section>

      <section id="process" className="max-w-7xl mx-auto px-6 py-12 grid grid-cols-1 md:grid-cols-2 gap-8 items-start text-center">
        <div className="mx-auto">
          <h2 className="text-2xl font-bold mb-4">From Quote To Clean Power In Four Steps</h2>
          <ul className="step-list list-disc pl-5 md:pl-0 md:inline-block space-y-2 text-slate-700 dark:text-slate-300">
            {steps.map((step) => (
              <li key={step}>{step}</li>
            ))}
          </ul>
        </div>
        <div className="stats-grid grid grid-cols-1 sm:grid-cols-3 gap-4">
          {stats.map((item, index) => (
            <div
              key={item.label}
              className="stat-card p-4 bg-gray-50 dark:bg-gray-900 rounded-lg text-center"
              ref={(el) => {
                statRef.current[index] = el;
              }}
            >
              <p className="stat-value text-xl font-bold">{item.value}</p>
              <p className="stat-label text-sm text-slate-500 dark:text-slate-400">{item.label}</p>
            </div>
          ))}
        </div>
      </section>

      <section id="pricing" className="max-w-7xl mx-auto px-6 py-16">
        <div className="text-center mb-10">
          <h2 className="text-3xl font-bold">Top Indian Brands & Install Costs</h2>
          <p className="mt-3 text-slate-600 dark:text-slate-400 max-w-2xl mx-auto">
            Compare estimated pre-subsidy installation costs per kW for India's leading solar providers. Costs vary based on system size, roof type, and location.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {brandCosts.map((brand, index) => (
            <div
              key={brand.name}
              ref={(el) => {
                brandsRef.current[index] = el;
              }}
              className="bg-white dark:bg-gray-900 border border-gray-100 dark:border-gray-800 rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow"
            >
              <h3 className="text-xl font-bold text-indigo-600 dark:text-indigo-400">{brand.name}</h3>
              <div className="mt-4 flex items-baseline gap-2">
                <span className="text-2xl font-extrabold">{brand.cost}</span>
                <span className="text-sm text-slate-500 dark:text-slate-400">/ kW</span>
              </div>
              <p className="mt-3 text-sm text-slate-600 dark:text-slate-300">{brand.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section id="contact" className="max-w-3xl mx-auto px-6 py-12">
        <div className="cta-panel bg-indigo-600 dark:bg-indigo-500 text-white rounded-lg p-8 text-center">
          <h2 className="text-2xl font-bold">Start Your Solar Home Journey Today</h2>
          <p className="mt-2">Tell us your current electricity bill and we will send a personalized payback plan in under 24 hours.</p>
          <button type="button" className="btn-primary mt-6 bg-white text-indigo-600 px-4 py-2 rounded-md font-semibold">Request My Plan</button>
        </div>
      </section>
      <footer className="mt-12 bg-slate-100 dark:bg-gray-900 text-slate-700 dark:text-slate-300">
        <div className="max-w-7xl mx-auto px-6 py-10">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div>
              <div className="font-bold text-lg">SOLAR NEST</div>
              <p className="mt-2 text-sm">Clean energy for modern homes — design, install, support.</p>
            </div>

            <div className="flex gap-8">
              <div>
                <h4 className="font-medium">Product</h4>
                <ul className="mt-2 space-y-2 text-sm">
                  <li><a href="#features" className="hover:underline">Features</a></li>
                  <li><a href="#process" className="hover:underline">Process</a></li>
                  <li><a href="#contact" className="hover:underline">Contact</a></li>
                </ul>
              </div>

              <div>
                <h4 className="font-medium">Company</h4>
                <ul className="mt-2 space-y-2 text-sm">
                  <li><a href="#" className="hover:underline">About</a></li>
                  <li><a href="#" className="hover:underline">Careers</a></li>
                  <li><a href="#" className="hover:underline">Blog</a></li>
                </ul>
              </div>
            </div>

            <div>
              <h4 className="font-medium">Get in touch</h4>
              <p className="mt-2 text-sm">support@solarnest.com</p>
              <div className="mt-4 flex items-center gap-3">
                <a aria-label="Twitter" href="#" className="p-2 rounded-md hover:bg-slate-200 dark:hover:bg-gray-800">
                  <svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor"><path d="M22 5.92a8.3 8.3 0 0 1-2.36.65 4.11 4.11 0 0 0 1.8-2.27 8.22 8.22 0 0 1-2.6.99A4.1 4.1 0 0 0 12.07 8a11.64 11.64 0 0 1-8.45-4.28 4.1 4.1 0 0 0 1.27 5.47 4.06 4.06 0 0 1-1.86-.51v.05a4.1 4.1 0 0 0 3.29 4.02 4.1 4.1 0 0 1-1.85.07 4.11 4.11 0 0 0 3.83 2.85A8.22 8.22 0 0 1 2 19.54a11.6 11.6 0 0 0 6.29 1.84c7.55 0 11.68-6.26 11.68-11.69v-.53A8.18 8.18 0 0 0 22 5.92z" /></svg>
                </a>
                <a aria-label="LinkedIn" href="#" className="p-2 rounded-md hover:bg-slate-200 dark:hover:bg-gray-800">
                  <svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor"><path d="M4.98 3.5a2.88 2.88 0 1 1 .02 0zM3.5 8.5h3v12h-3zM9 8.5h2.86v1.64h.04c.4-.76 1.38-1.56 2.85-1.56 3.04 0 3.6 2 3.6 4.6v6.32h-3v-5.6c0-1.34 0-3.06-1.86-3.06-1.86 0-2.15 1.46-2.15 2.96v5.7h-3z" /></svg>
                </a>
              </div>
            </div>
          </div>

          <div className="mt-8 border-t border-slate-200 dark:border-gray-800 pt-6 text-sm text-center text-slate-600 dark:text-slate-400">
            © {new Date().getFullYear()} Solar Nest. All rights reserved.
          </div>
        </div>
      </footer>
    </main>
  );
}

export default App;
